### ISSUE TITLE
how to use mutiple cores

### ISSUE THREAD

**Issue by zheng-xiao-sheng** [xuxif/DeepMEI#2]
in docker mode, i cannot find the wat to activate the mutiple cores

**Comment by xuxif** [comment]
默认就是使用20个线程，已经很多了，再多的话硬盘IO跟不上。之前我们测试30X WGS30分钟左右就能跑完。如果想同时跑多个样本，可以尝试同时运行多个docker。The default is already using 20 threads, which is already quite high. Adding more threads could potentially overload the disk I/O. In our previous testing, we were able to complete a 30X whole-genome sequencing in around 30 minutes. If you want to run multiple samples simultaneously, you can try running multiple Docker containers at the same time.

Please note that this is a translation of the provided text. If you have any specific requirements or if there are any additional details you would like to include in the response, please let me know and I'll be happy to assist you further.

**Comment by xuxif** [comment]
默认就是使用20个线程，已经很多了，再多的话硬盘IO跟不上。之前我们测试30X WGS30分钟左右就能跑完。如果想同时跑多个样本，可以尝试同时运行多个docker。The default is already using 20 threads, which is already quite high. Adding more threads could potentially overload the disk I/O. In our previous testing, we were able to complete a 30X whole-genome sequencing in around 30 minutes. If you want to run multiple samples simultaneously, you can try running multiple Docker containers at the same time.

**Comment by zheng-xiao-sheng** [comment]
好的，谢谢
