### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by BenpengMiao** [xuxif/DeepMEI#4]
Dear author,

I plan to try your docker image but I can not use sudo docker in our server. I also pull your docker in my server but can not access the /root/data

How can I run your docker image?

Thanks!

**Comment by xuxif** [comment]
如果你没有管理员权限，使用 docker 版本的 DeepMEI 可能不合适。建议你使用 conda安装DeepMEI 所需要的依赖，然后从 github 拉取 DeepMEI 代码，详细步骤可以在 DeepMEI 的使用方法里面找到。目前 conda 和 docker 版本都已经更新到了相同的版本，自己安装确实会比较麻烦。但是 docker 需要你拥有管理员权限（sudo），这个是硬性的要求。你可以尝试非 docker 的安装方式，如果有任何问题你可以直接给我发邮件(2623716586@qq.com)或者在后面留言。
If you don't have administrator privileges, using the Docker version of DeepMEI might not be suitable. It is recommended that you use conda to install the dependencies required for DeepMEI and then pull the DeepMEI code from GitHub. Detailed steps can be found in the DeepMEI usage guide. Currently, both the conda and Docker versions have been updated to the same version, and self-installation can indeed be more complicated. However, Docker requires you to have administrator privileges (sudo), which is a rigid requirement. You can try the non-Docker installation method. If you encounter any issues, you can directly email me (2623716586@qq.com) or leave a comment below.

**Comment by BenpengMiao** [comment]
Thanks! 
Is there any plan to update the docker image without the sudo? The server I used is built based on the docker image, I can not use conda to install the deepMEI.
Best

**Comment by xuxif** [comment]
You might have misunderstood my point; it's Docker that requires sudo privileges, not DeepMEI. Alternatively, you could show me the specific error message you're encountering—perhaps I misunderstood the permission issue you're facing.

**Comment by BenpengMiao** [comment]
I use the following code to pull the docker image in our server:
`LSF_DOCKER_PRESERVE_ENVIRONMENT=false LSF_DOCKER_VOLUMES="/storage1/fs1/smaht/Active:/storage1/fs1/smaht/Active /home/benpeng:/home/benpeng" bsub -n 2 -G compute-hprc -q general-interactive -Is -M 30G -R "select[mem>30G] rusage[mem=30G] span[hosts=1]" -a "docker(xuxiaofeiscu/deepmei:latest)" bash`

Then, I run this:
`sudo docker run -it  -v /storage1/fs1/smaht/Active/shared/MEI/BAM/UWSC/:/root/data/ -w /root xuxiaofeiscu/deepmei:latest  /bin/bash -c 'export PATH=/root/miniconda3/bin:$PATH;./DeepMEI/DeepMEI -i /root/data/SMHTHAPMAP6-X-X-NN-A001-uwsc-SMAFIAY72ZLB-sentieon_bwamem_202308.01_GRCh38.aligned.sorted.bam  -r 38 -w /root/data/'`

bash: sudo: command not found

**Comment by xuxif** [comment]
Based on the code you provided, I guess you might be using a computing cluster. The prompt 'bash: sudo: command not found' suggests two possibilities:

You are logged in as the root user, in which case you can run Docker directly. Just remove sudo and keep the command unchanged.
You do not have administrator privileges, in which case I recommend using the conda version to install dependencies.
I don't quite understand why your server cannot use conda. Perhaps you can explain the reason to me—it might be some type of virtual machine?

**Comment by BenpengMiao** [comment]
I do not have administrator privileges.
Not the virtual machine, the server I used is designed for people who need access to high-performance computing resources and storage for large data sets. The server provides a Docker image that can be used to run applications on the cluster.

**Comment by xuxif** [comment]
Submit a job without sudo and tell me the error message
docker run -it  -v /storage1/fs1/smaht/Active/shared/MEI/BAM/UWSC/:/root/data/ -w /root xuxiaofeiscu/deepmei:latest  /bin/bash -c 'export PATH=/root/miniconda3/bin:$PATH;./DeepMEI/DeepMEI -i /root/data/SMHTHAPMAP6-X-X-NN-A001-uwsc-SMAFIAY72ZLB-sentieon_bwamem_202308.01_GRCh38.aligned.sorted.bam  -r 38 -w /root/data/'

**Comment by BenpengMiao** [comment]
bash: docker: command not found

I think maybe It need to build a new docker image following the conda installation
