### ISSUE TITLE
Don't find environment.yaml

### ISSUE THREAD

**Issue by knakamura6222053** [xuxif/DeepMEI#5]
The error occurs because environment.yaml is missing. How can I solve this?
The same thing happened with docker.

**Comment by xuxif** [comment]
Could you please send me the error message? The current version of DeepMEI doesn't seem to require an environment.yaml file. The Conda version can install all dependencies with conda install deepmei, and the Docker version has resolved all dependencies. I'm wondering if you need a separate environment.yaml file or a configuration file for docker build.

Additionally, a new version of DeepMEI is coming soon. I recommend pulling the code again later.

**Comment by knakamura6222053** [comment]
Thanks developers!

I get error message


############################################################################################
conda install deepmei

Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - deepmei

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

############################################################################################

I look forward to the updated version because I would like to use DeepMEI to analyze the genome of mitochondrial diseases.

**Comment by xuxif** [comment]
I recommend resolving the dependencies for DeepMEI using the deepmei.yml file, which can be downloaded from the DeepMEI GitHub page. You can create the environment with the command conda env create -f deepmei.yml. After that, clone the DeepMEI code from GitHub. The code has been updated, so you can try the latest version.

Based on my experience with analyzing the 1000 Genomes Project data, mobile element insertions (MEI) in mitochondrial DNA seem to be very rare. You might need to use multiple tools to analyze your sample effectively.
