### ISSUE TITLE
Start Candidate insertion searching Error

### ISSUE THREAD

**Issue by knakamura6222053** [xuxif/DeepMEI#6]
Dear developer.

I am doing a run with docker.
So I got an error in the Start candidate insertion searching process.
ERROR: Requested column 4, but database file - only has fields 1 - 0.

Maybe Use default mobile element reference:/root /DeepMEI/DeepMEI_model/reference/ME_add_ALU.fa
part of the file may be related to this?
For example, ME_chr.bed.

Best regards.

**Comment by xuxif** [comment]
Could you please provide details about the input BAM file? For example, what species it belongs to (human or other), and which reference genome version you're using. Additionally, could you share the command you used to run DeepMEI?

**Comment by knakamura6222053** [comment]
Thanks for the quick response.

It is GRCh38 with the human bam file.

The commands used are as follows.

> docker run -it -v /lustre/home/kouta/:/root/data xuxiaofeiscu/deepmei:latest /bin/bash  -c 'export PATH=/root/miniconda3/bin:$PATH; ./DeepMEI/DeepMEI -I /root/data/sample.bam -r 38 -w /root/data/' 



Best regards

**Comment by xuxif** [comment]
Try the following command:
 docker run -it -v /lustre/home/kouta/:/root/data -w /root xuxiaofeiscu/deepmei:latest /bin/bash -c 'export PATH=/root/miniconda3/bin:$PATH; ./DeepMEI/DeepMEI -i /root/data/sample.bam -r 38 -w /root/data/'

**Comment by knakamura6222053** [comment]
Thanks Developer.

I try that command, but get same Error message.

ERROR: Requested column 4, but database file -only has fields 1 - 0.


Best regards

**Comment by xuxif** [comment]
If it's convenient, you could share the BAM file for this sample with me. Alternatively, you can extract the main chromosomes (chr1-22, chrX, chrY, chrM) from this BAM file into a new BAM file, and then reanalyze the newly generated file using DeepMEI. I suspect there might be some inconsistency between your reference genome and the contigs in the Docker image. Another option is to send me the intermediate files. To do this, you need to enter the recently run Docker container (docker ps -a), then run docker start container_id, followed by docker exec -it container_id /bin/bash. Navigate to /root/DeepMEI/DeepMEI_script/, and package the files candidate_pos and vsoft_pos in this directory and send them to my email at 2623716586@qq.com.
